; This file was auto-generated by drush make
api = 2
core = 7.x

;This is just to try the make file locally and it will be removed in the final version
;projects[drupal][version] = 7.22

; Patterns: contrib modules dependencies

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.1"

projects[macro][subdir] = "contrib"
projects[macro][version] = "1.0-alpha2"

;This branch of the installation profile is based on 7.x-2.x-dev. This will need to be udpated to point to the new release
projects[patterns][subdir] = "contrib"
projects[patterns][version] = "2.x-dev"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

; Default languages offered during the installation.
; Currently not supported, .po files related to Drupal version included in translations

;projects[es][subdir] = "translations"
;projects[zh-hans][subdir] = "translations"


; qscience and qtr: contrib modules dependencies - @TO-DO: ask @qscience list to confirm specific versions
projects[auto_nodetitle][subdir] = "contrib"
projects[auto_nodetitle][version] = "1.0"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.0"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.0"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

projects[eva][subdir] = "contrib"
projects[eva][version] = "1.2"

projects[filefield_sources][subdir] = "contrib"
projects[filefield_sources][version] = "1.7"

projects[date][subdir] = "contrib"
projects[entity][version] = "2.6"

projects[ctools][subdir] = "contrib"
projects[entity][version] = "1.3"

projects[plus1][subdir] = "contrib"
projects[entity][version] = "1.0-alpha1"

projects[votingapi][subdir] = "contrib"
projects[votingapi][version] = "2.11"

; pdfparser: contrib modules dependencies - @TO-DO: ask @qscience list to confirm specific versions
projects[field_remove_item][subdir] = "contrib"
projects[field_remove_item][version] = "1.0-rc1"

; qscience_profile_theme: base theme dependency
projects[shiny][version] = "1.1"

; Libraries

; Spyc (YAML parser): required by patterns_yamlparser submodule
libraries[spyc][download][type] = "get"
libraries[spyc][download][url] = "https://raw.github.com/mustangostang/spyc/master/Spyc.php"
libraries[spyc][directory_name] = "spyc"
libraries[spyc][type] = "library"

; Waiting for answer in issue: http://drupal.org/node/1945806
; Create an optional task in the profile if it is not acceptable in the whitelist 
;libraries[codemirror][download][type] = "git"
;libraries[codemirror][download][url] = "http://marijnhaverbeke.nl/git/codemirror"
;libraries[codemirror][directory_name] = "codemirror"
;libraries[codemirror][type] = "library"
